version: '3.4'

services:
  realestate.webapi:
    image: realestate:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RealEstate.WebAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/pragmuti/Calismalarim/workspaces/c#/RealEstate/backEnd/RealEstate/src/Web/RealEstate.WebAPI:/app
      - /Users/pragmuti/Calismalarim/workspaces/c#/RealEstate/backEnd/RealEstate:/src
      - /Users/pragmuti/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/pragmuti/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net7.0/RealEstate.WebAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true