apiVersion: v1
kind: Service
metadata:
  name: real-estate-api
  namespace: fuzulev
spec:
  ports:
  - nodePort: 30830
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: real-estate-api
  sessionAffinity: None
  type: NodePort